[phases.setup]
nixPkgs = [
    "python310", 
    "gcc", 
    "cmake", 
    "pkg-config", 
    "protobuf",
    "git",
    "openjdk"
]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip wheel setuptools",
    ". /opt/venv/bin/activate && pip install 'numpy>=1.21.0,<2.0.0' --no-cache-dir",
    ". /opt/venv/bin/activate && pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu",
    ". /opt/venv/bin/activate && pip install sentencepiece --no-cache-dir",
    ". /opt/venv/bin/activate && pip install sentence-transformers==2.2.2 --no-cache-dir",
    ". /opt/venv/bin/activate && pip install -r requirements.txt --no-cache-dir"
]

[phases.build]
cmds = [
    "mkdir -p /opt/venv/model_cache",
    ". /opt/venv/bin/activate && python -c \"import os; os.environ['SENTENCE_TRANSFORMERS_HOME']='/opt/venv/model_cache'; from sentence_transformers import SentenceTransformer; print('Downloading KR-SBERT...'); model = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS'); print('Model cached successfully!')\""
]

[start]
cmd = "export SENTENCE_TRANSFORMERS_HOME=/opt/venv/model_cache && streamlit run app.py --server.port $PORT --server.address 0.0.0.0"