[phases.setup]
nixPkgs = [
    "python310", 
    "gcc", 
    "cmake", 
    "pkg-config", 
    "protobuf",
    "git",
    "openjdk"
]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip wheel setuptools",
    ". /opt/venv/bin/activate && pip install 'numpy>=1.21.0,<2.0.0' --no-cache-dir",
    ". /opt/venv/bin/activate && pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu",
    ". /opt/venv/bin/activate && pip install sentencepiece --no-cache-dir",
    ". /opt/venv/bin/activate && pip install -r requirements.txt --no-cache-dir"
]

[start]
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"